import { BaseAgent } from '../baseAgent.js';
import { complete } from '../../lib/llm.js';

const SYSTEM = `You are agent-research in an autonomous micro-SaaS factory.
Find ONE profitable micro-SaaS opportunity: a real, narrow problem with a
reachable audience and low competition. Be concrete and skeptical — no hype.`;

const PROMPT = `Produce a TrendReport in GitHub-flavored Markdown with exactly these sections:
# TrendReport
## Problem statement
## Target audience
## Niche signal   (3-4 bullets: where the demand/low-competition signal shows up)
## Monetization viability   (model, price range, market size, confidence: low/medium/high)

End with: "_Generated by agent-research. Requires CEO kickoff approval._"
Keep it under 250 words. Output only the Markdown, no preamble.`;

// Deterministic fallback used when no API key is configured (offline / tests).
const STUB = [
  '# TrendReport',
  '',
  '## Problem statement',
  'Small agencies lack a lightweight tool to schedule + recycle social content.',
  '',
  '## Target audience',
  'Solo marketers and 2-10 person agencies.',
  '',
  '## Niche signal',
  '- Product Hunt: rising "content recycling" launches',
  '- GitHub: little maintained OSS in this space',
  '- Keyword: "evergreen content scheduler" — high volume, low competition',
  '',
  '## Monetization viability',
  'SaaS, $19-49/mo tiers. Reachable market: medium. Confidence: medium.',
  '',
  '_Generated by agent-research. Requires CEO kickoff approval._',
].join('\n');

// agent-research — DISCOVERY. Live LLM call, stub fallback.
export class ResearchAgent extends BaseAgent {
  async run() {
    const report = await complete({ system: SYSTEM, prompt: PROMPT, source: this.id });
    return [await this.emit('TrendReport.md', report ?? STUB)];
  }
}
