// Ideas store helpers. The research agent appends a structured idea each run;
// the dashboard reads them and the CEO approves/rejects from the Ideas tab.
// Pure functions — callers own persistence (agent emit / dashboard write) so
// every write still flows through the Gatekeeper or the dashboard endpoint.
//
// Two idea shapes exist in the wild:
//   - current: nested { idea, distribution, revenuePath, monthSixSignal,
//     score, risksAndDefensibility }
//   - legacy:  flat { title, problem, audience, niche, model, priceRange,
//     marketSize, distribution, edgeFit, revenuePath, monthSixSignal, risks }
// Ideas persisted before 2026-08-29 use the legacy shape, so both render.

const STATUSES = ['new', 'approved', 'rejected', 'in-pipeline', 'shipped'];

// True when the object uses the current nested shape.
function isNested(idea) {
  return Boolean(idea && typeof idea.idea === 'object' && idea.idea !== null);
}

// Title / score live at different depths per shape. Used for the top-level
// mirrors the dashboard and archiver read.
export function ideaTitle(idea) {
  return idea?.idea?.title ?? idea?.title ?? 'Untitled idea';
}

export function ideaScore(idea) {
  return typeof idea?.score === 'number' ? idea.score : 0;
}

function bullets(list) {
  return (list ?? []).map((n) => `- ${n}`).join('\n');
}

function renderNested(i) {
  return [
    '# TrendReport',
    '',
    `## ${i.idea?.title ?? 'Untitled idea'}`,
    i.idea?.oneLiner ?? '',
    '',
    '## Value proposition',
    i.idea?.valueProposition ?? '',
    '',
    '## Distribution — first 10 paying customers',
    i.distribution?.first10CustomersTactic ?? '',
    '',
    '### Channels',
    bullets(i.distribution?.specificChannelsOrPlatforms),
    '',
    '## Revenue path',
    `Pricing: ${i.revenuePath?.pricingModel ?? 'unknown'}`,
    `Time to first dollar: ${i.revenuePath?.timeToFirstDollarDays ?? '?'} days`,
    '',
    i.revenuePath?.path2Profitability ?? '',
    '',
    '## Month-6 survival signal',
    i.monthSixSignal?.survivalMetric ?? '',
    '',
    `**Kill condition:** ${i.monthSixSignal?.killCondition ?? ''}`,
    '',
    '## Competition',
    `**Saturation:** ${i.competition?.saturation ?? 'not assessed'}`,
    '',
    '### Already solving this',
    bullets(i.competition?.existingSolutions),
    '',
    '### Why a buyer would switch',
    bullets(i.competition?.whyTheyLose),
    '',
    '## Risks and defensibility',
    `**Primary fatal risk:** ${i.risksAndDefensibility?.primaryFatalRisk ?? ''}`,
    '',
    `**Defensibility:** ${i.risksAndDefensibility?.defensibilityStrategy ?? ''}`,
    '',
    `_Score: ${ideaScore(i)}/100. Generated by agent-research. Requires CEO kickoff approval._`,
  ].join('\n');
}

function renderLegacy(idea) {
  return [
    '# TrendReport',
    '',
    '## Problem statement',
    idea.problem ?? '',
    '',
    '## Target audience',
    idea.audience ?? '',
    '',
    '## Niche signal',
    bullets(idea.niche),
    '',
    '## Monetization viability',
    `${idea.model ?? ''}. Reachable market: ${idea.marketSize ?? 'unknown'}. Confidence: ${idea.confidence ?? 'unknown'}.`,
    '',
    '## Distribution — first 10 customers',
    idea.distribution ?? '',
    '',
    '## Edge fit',
    idea.edgeFit ?? '',
    '',
    '## Revenue path',
    idea.revenuePath ?? '',
    '',
    '## Month-6 go/no-go signal',
    idea.monthSixSignal ?? '',
    '',
    '## Risks',
    bullets(idea.risks),
    '',
    '_Generated by agent-research. Requires CEO kickoff approval._',
  ].join('\n');
}

// Render an idea object into the markdown TrendReport the pipeline consumes.
export function renderReport(idea) {
  return isNested(idea) ? renderNested(idea) : renderLegacy(idea);
}

// Return a NEW store with the idea appended (assigns id/createdAt/status).
// The whole idea object is preserved — an earlier version whitelisted fields,
// which silently dropped anything the schema added. `title` and `score` are
// mirrored to the top level because the dashboard and archiver read them there.
export function appendIdea(store, idea, report) {
  const ideas = Array.isArray(store?.ideas) ? store.ideas : [];
  const n = ideas.length + 1;
  const entry = {
    ...idea,
    id: `idea-${String(n).padStart(3, '0')}`,
    createdAt: new Date().toISOString(),
    title: ideaTitle(idea),
    score: ideaScore(idea),
    status: 'new',
    report: report ?? renderReport(idea),
  };
  return { ideas: [...ideas, entry] };
}

// Return a NEW store with one idea's status changed. No-op if id/status invalid.
export function setIdeaStatus(store, id, status) {
  if (!STATUSES.includes(status)) return store;
  const ideas = (store?.ideas ?? []).map((i) =>
    i.id === id ? { ...i, status, decidedAt: new Date().toISOString() } : i,
  );
  return { ideas };
}

export { STATUSES };
