// Ideas store helpers. The research agent appends a structured idea each run;
// the dashboard reads them and the CEO approves/rejects from the Ideas tab.
// Pure functions — callers own persistence (agent emit / dashboard write) so
// every write still flows through the Gatekeeper or the dashboard endpoint.

const STATUSES = ['new', 'approved', 'rejected', 'in-pipeline', 'shipped'];

// Render an idea object into the markdown TrendReport the pipeline consumes.
export function renderReport(idea) {
  const niche = (idea.niche ?? []).map((n) => `- ${n}`).join('\n');
  return [
    '# TrendReport',
    '',
    '## Problem statement',
    idea.problem ?? '',
    '',
    '## Target audience',
    idea.audience ?? '',
    '',
    '## Niche signal',
    niche,
    '',
    '## Monetization viability',
    `${idea.model ?? ''}. Reachable market: ${idea.marketSize ?? 'unknown'}. Confidence: ${idea.confidence ?? 'unknown'}.`,
    '',
    '_Generated by agent-research. Requires CEO kickoff approval._',
  ].join('\n');
}

// Return a NEW store with the idea appended (assigns id/createdAt/status).
export function appendIdea(store, idea, report) {
  const ideas = Array.isArray(store?.ideas) ? store.ideas : [];
  const n = ideas.length + 1;
  const entry = {
    id: `idea-${String(n).padStart(3, '0')}`,
    createdAt: new Date().toISOString(),
    title: idea.title ?? 'Untitled idea',
    problem: idea.problem ?? '',
    audience: idea.audience ?? '',
    niche: idea.niche ?? [],
    model: idea.model ?? '',
    priceRange: idea.priceRange ?? '',
    marketSize: idea.marketSize ?? '',
    confidence: idea.confidence ?? 'unknown',
    score: typeof idea.score === 'number' ? idea.score : 0,
    status: 'new',
    report: report ?? renderReport(idea),
  };
  return { ideas: [...ideas, entry] };
}

// Return a NEW store with one idea's status changed. No-op if id/status invalid.
export function setIdeaStatus(store, id, status) {
  if (!STATUSES.includes(status)) return store;
  const ideas = (store?.ideas ?? []).map((i) =>
    i.id === id ? { ...i, status, decidedAt: new Date().toISOString() } : i,
  );
  return { ideas };
}

export { STATUSES };
